const dataJLV = {
    sobreMi: ` <p>💻 Soy un Desarrollador Full Stack con mayor especialización en el stack MERN (MongoDB, Express.js, React.js, Node.js).<br>
    Mi enfoque está en el diseño web creativo y funcional. Me encanta enfrentar nuevos desafíos y cada línea de código que escribo refleja mi compromiso con el crecimiento y la mejora continua. <br>
    <i>Estoy aquí para ayudarte a dar vida a tus proyectos con profesionalismo y creatividad. Si necesitas un colaborador apasionado y dedicado, ¡no dudes en contactarme!</i></p>
    `,
    educación: [
      { 
        titulo: "DESARROLLADOR WEB FULL STACK MERN",
        fecha: "Julio - Septiembre 2023",
        instituto: "MindHub LA",
        descripcion: "Bootcamp intensivo en el desarrollo e implementación del stack MERN (MongoDB, Express.js, React.js, Node.js), construyendo una base sólida para el desarrollo de aplicaciones web modernas."
      },
      {
        titulo: "DESARROLLADOR WEB FRONTEND",
        fecha: "Enero - Marzo 2023",
        instituto: "MindHub LA",
        descripcion: "Bootcamp centrado en el aprendizaje Frontend mediante la metodología de proyectos reales, evolucionando en dificultad para adquirir las habilidades de un Desarrollador Web."
      },
      { 
        titulo: "DESARROLLADOR WEB FULL STACK",
        fecha: "Diciembre 2021 - Junio 2022",
        instituto: "Argentina Programa 4.0",
        descripcion: "Curso de Desarrollador Web Full-Stack donde se estudian tecnologías de desarrollo Frontend y Backend."
      },
      { 
        titulo: "TÉCNICO UNIVERSITARIO EN MANTENIMIENTO INDUSTRIAL",
        fecha: "2015 - 2018",
        instituto: "ITU - Instituto Tecnológico Universitario (Universidad Nacional de Cuyo)",
        descripcion: "Aptitudes en electricidad, mecánica, automatización, informática, electrónica, entre otras."
      },
    ],
    experiencia: [
      { 
        titulo: "Desarrollador Freelance",
        fecha: "2023 - Presente",
        instituto: "",
        descripcion: `Desarrollador Web Freelance apasionado y especializado en la creación de proyectos dinámicos e innovadores. Destaco por la aplicación práctica de mis conocimientos, demostrando habilidades sólidas en la resolución de problemas y una adaptabilidad proactiva a las tendencias tecnológicas emergentes. `
      },
    ],
    habilidades: {
      frontend: [
        { name: "HTML5",
          url: `https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg`,
        },
        { name: "CSS3",
          url: `https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg`,
        },
        { name: "Javascript",
          url: `https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg`,
        },
        { name: "React.js",
          url: `https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg`,
        },
        { name: "Redux",
          url: `https://cdn.jsdelivr.net/gh/devicons/devicon/icons/redux/redux-original.svg`,
        },
        { name: "Angular",
          url: `https://cdn.jsdelivr.net/gh/devicons/devicon/icons/angularjs/angularjs-original.svg`,
        },
        { name: "Typescript",
          url: `https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg`,
        },
        { name: "Tailwind CSS",
          url: `https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tailwindcss/tailwindcss-original.svg`,
        },
        { name: "Bootstrap",
          url: `https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bootstrap/bootstrap-original.svg`,
        },
        { name: "Sass",
          url: `https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sass/sass-original.svg`,
        },
        { name: "Vite",
          url: `https://avatars.githubusercontent.com/u/65625612?s=280&v=4`,
        },
        
      ],
      backend: [
        { name: "Node.js",
          url: `https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg`,
        },
        { name: "Express.js",
          url: `https://adware-technologies.s3.amazonaws.com/uploads/technology/thumbnail/20/express-js.png`,
        },
        { name: "MongoDB",
          url: `https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original-wordmark.svg`,
        },
        { name: "Java",
          url: `https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg`,
        },
        { name: "MySQL",
          url: `https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original-wordmark.svg`,
        },
        { name: "JWT",
          url: `https://seeklogo.com/images/J/jwt-logo-65D86B4640-seeklogo.com.png`,
        },
        { name: "Postman",
          url: `https://cdn.worldvectorlogo.com/logos/postman.svg`,
        },
      ],
      otras: [
        { name: "Inglés Técnico",
          url: `https://cdn-icons-png.flaticon.com/512/8716/8716483.png`,
        },
        { name: "Git",
          url: `https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg`,
        },
        { name: "Github",
          url: `https://cdn4.iconfinder.com/data/icons/iconsimple-logotypes/512/github-512.png`,
        },
        { name: "NPM",
          url: `https://cdn.jsdelivr.net/gh/devicons/devicon/icons/npm/npm-original-wordmark.svg`,
        },
        
        { name: "Visual Studio Code",
          url: `https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vscode/vscode-original.svg`,
        },
        
        { name:"Metodología SCRUM",
          url:"https://seeklogo.com/images/S/scrum-logo-B057CBD9B8-seeklogo.com.png"
        },
      ]
    },
    proyectos: [
      {
        nombre: "Resto Delicious",
        descripcion: `Landing Page para un Restaurante, diseñada con React para el frontend y estilizada con Tailwind CSS. Se han integrado librerías como Redux para la gestión de estados, así como otras para la aplicación de ciertos efectos y transiciones específicas.`,
        img: "assets/img/proyect7.jpg",
        tecnologias: [
          { name: "React",
            url: `https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg`,
          },
          { name: "Redux",
            url: `https://cdn.jsdelivr.net/gh/devicons/devicon/icons/redux/redux-original.svg`,
          },
          { name: "Javascript",
            url: `https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg`,
          },
          { name: "Tailwind",
            url: `https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tailwindcss/tailwindcss-original.svg`,
          },
        ],
        demo: "https://resto-delicious.netlify.app/",
        repo: "https://github.com/JosephV95",
      },
      {
        nombre: "MyTinerary",
        descripcion: `Proyecto Full Stack con Frontend desarrollado en React y haciendo uso de Redux para el manejo de estados. 
          En Backend, se creó una API REST totalmente funcional con operaciones CRUD (Crear, Leer, Actualizar, Eliminar) para gestionar la información. Se emplearon Node.js y Express, con MongoDB como base de datos.`,
        img: "assets/img/proyect5.jpg",
        tecnologias: [
          { name: "React",
            url: `https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg`,
          },
          { name: "Javascript",
            url: `https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg`,
          },
          { name: "Redux",
            url: `https://cdn.jsdelivr.net/gh/devicons/devicon/icons/redux/redux-original.svg`,
          },
          { name: "Node",
          url: `https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg`,
          },
          { name: "Express",
            url: `https://adware-technologies.s3.amazonaws.com/uploads/technology/thumbnail/20/express-js.png`,
          },
          { name: "MongoDB",
            url: `https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original-wordmark.svg`,
          },
          { name: "JWT",
            url: `https://seeklogo.com/images/J/jwt-logo-65D86B4640-seeklogo.com.png`,
          },
          { name: "Bootstrap",
            url: `https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bootstrap/bootstrap-original.svg`,
          },
          { name: "CSS",
            url: `https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg`,
          },
        ],
        demo: "https://mytinerarydev.netlify.app/",
        repo: "https://github.com/JosephV95/mytinerary-joseVilte",
      },
      {
        nombre: "Harry Potter Data",
        descripcion: "Proyecto de aplicación web de página única (SPA) que destaca por su enrutamiento integrado con Angular y la integración de una API para obtener datos de personajes. Cuenta con una variedad de filtros, los cuales pueden combinarse para mejorar la experiencia del usuario.",
        img: "assets/img/proyect4.jpg",
        tecnologias: [
          { name: "Angular",
            url: `https://cdn.jsdelivr.net/gh/devicons/devicon/icons/angularjs/angularjs-original.svg`,
          },
          { name: "Typescript",
            url: `https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg`,
          },
          { name: "Bootstrap",
            url: `https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bootstrap/bootstrap-original.svg`,
          },
          { name: "HTML5",
          url: `https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg`,
          },
          { name: "Sass",
            url: `https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sass/sass-original.svg`,
          },
        ],
        demo: "https://harrypotter-data.web.app/home",
        repo: "https://github.com/JosephV95/Harry-Potter-Data.git",
      },
      {
        nombre: "Mi Portfolio",
        descripcion: `El frontend de mi portfolio actual está creado con HTML y CSS, incorporando funcionalidad e interactividad mediante Javascript Vanilla.`,
        img: "assets/img/proyect6.jpg",
       tecnologias: [
          { name: "HTML5",
            url: `https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg`,
          },
          { name: "CSS3",
            url: `https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg`,
          },
          { name: "Javascript",
            url: `https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg`,
          },
          { name: "Bootstrap",
            url: `https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bootstrap/bootstrap-original.svg`,
          },
       ],
        demo: "https://viltejosedev.netlify.app",
        repo: "https://github.com/JosephV95/VilteJoseDev.git",
      },
      {
        nombre: "Amazing Events",
        descripcion: `Proyecto Frontend implementado con Vue js (<i>en repositorio se encuentra disponible el desarrollo en 
            Javascript Vanilla</i>), la información de los eventos se obtiene de una API. 
            La web cuenta con dos tipos de filtros combinables.`,
        img: "assets/img/proyect3.jpg",
       tecnologias: [
          { name: "Vue.js",
            url: `https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vuejs/vuejs-original.svg`,
          },
          { name: "HTML5",
            url: `https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg`,
          },
          { name: "CSS3",
            url: `https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg`,
          },
          { name: "Javascript",
            url: `https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg`,
          },
          { name: "Bootstrap",
            url: `https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bootstrap/bootstrap-original.svg`,
          },
       ],
        demo: "https://josephv95.github.io/Mindhub-Javascript-Task/",
        repo: "https://github.com/JosephV95/Mindhub-Javascript-Task.git",
      },
    ]
  }